CREDIT_CARD_BANK_ACC_MAPPING_FILENAME = 'db/cards_20240204.csv'

POALIM_FILE_PREFIX = 'poalim'
LEUMI_FILE_PREFIX = 'leumi'
MERCANTILE_FILE_PREFIX = 'mercantile'

EXPENSES_OUT_FILE_PREFIX = 'expenses'
INCOME_OUT_FILE_PREFIX = 'income'